name = "火狱骑行"
version = "1.2"
special_program = 2024-09-13T19:30:00
update_time = 2024-09-25T06:00:00
wish_name = "调频"

[[wish]]
type = "代理人"
name = "「荣焰桂冠」"
start = 2024-09-25T11:00:00
end = 2024-10-16T11:59:59
describe = "[凯撒(防护·物理)]、[派派(异常·物理)]、[安东(强攻·电)]"

[[wish]]
type = "音擎"
name = "「喧哗奏鸣」"
start = 2024-09-25T11:00:00
end = 2024-10-16T11:59:59
describe = "[奔袭獠牙(防护)]、[轰鸣座驾(异常)]、[旋钻机-赤轴(强攻)]"

[[wish]]
type = "代理人"
name = "「天生丽炽」"
start = 2024-10-16T12:00:00
end = 2024-11-05T14:59:59
describe = "[柏妮思(异常·火)]、[露西(支援·火)]、[妮可(支援·以太)]"

[[wish]]
type = "音擎"
name = "「喧哗奏鸣」"
start = 2024-10-16T12:00:00
end = 2024-11-05T14:59:59
describe = "[灼心摇壶(异常)]、[好斗的阿炮(支援)]、[聚宝箱(支援)]"

[[event]]
type = "活动"
name = "「『霸主』的欢宴」活动"
start = 2024-09-26T11:00:00
end = 2024-11-04T03:59:59
describe = "经营外环餐厅「芝托邦」，亲手打造「霸主」的宴会厅。"

[[event]]
type = "活动"
name = "「全新放送」活动"
start = 2024-09-25T11:00:00
end = 2024-11-05T03:59:59
describe = "「全新放送」活动期间，累计登录7天即可获得[加密母带]*10！"

[[event]]
type = "活动"
name = "「切勿独行」活动"
start = 2024-09-30T10:00:00
end = 2024-10-14T03:59:59
describe = "「金手指」电玩店小游戏上新，「怪奇旅伴」即将上线！相关限时任务同步开放，完成即可获得对应奖励。"

[[event]]
type = "活动"
name = "「数据悬赏-实战模拟」活动"
start = 2024-09-30T04:00:00
end = 2024-10-05T03:59:59
describe = "「数据悬赏-实战模拟」活动期间，绳匠进入「实战模拟室」，选择任意怪物卡并成功通过挑战，即可获得双倍奖励！"

[[event]]
type = "活动"
name = "「赠尔·丽都」活动"
start = 2024-10-07T10:00:00
end = 2024-10-21T03:59:59
describe = "活动期间，可在六分街的报刊亭完成《丽都导览》合订本附赠的拼图游戏。"

[[event]]
type = "活动"
name = "「漫行于以太虚境」活动"
start = 2024-10-16T10:00:00
end = 2024-10-28T03:59:59
describe = "活动期间，绳匠可以通过空洞深潜系统捕捉病毒，对被病毒侵蚀的记事信息进行修复。"

[[event]]
type = "活动"
name = "「『嗯呢』从天降」活动"
start = 2024-10-16T10:00:00
end = 2024-11-05T03:59:59
describe = "「『嗯呢』从天降」活动期间，累计登录7天即可获得[邦布券]*10！"

[[event]]
type = "活动"
name = "「先遣赏金-定期清剿」活动"
start = 2024-10-21T04:00:00
end = 2024-10-26T03:59:59
describe = "「先遣赏金-定期清剿」活动期间，绳匠进入「定期清剿」，挑战并通过任意关卡即可获得双倍奖励！"

[[event]]
type = "活动"
name = "「内有恶犬」活动"
start = 2024-10-25T10:00:00
end = 2024-11-01T03:59:59
describe = "活动期间，绳匠可以在电玩店「金手指」游玩活动模式「噬魂犬3-群猎」，与随机匹配的另外三名绳匠进行互不结盟的四人联机对战。每场对战结束时，不同排名的绳匠将获得不同数量的犬犬兑换券（第1-4名依次获得数量为750、650、550、500的犬犬兑换券奖励)。"

[[event]]
type = "活动"
name = "「『141』友情联络」活动"
start = 2024-10-27T10:00:00
end = 2024-11-04T03:59:59
describe = "活动期间，绳匠完成活动委托后，可以获得店主们的[回信]；把[回信]交给丝琪，即可领取[菲林]、[邦布券]和各类养成材料奖励。"




