name = "虚拟杀机"
version = "1.3"
special_program = 2024-10-25T19:30:00
update_time = 2024-11-06T06:00:00
wish_name = "调频"

[[wish]]
type = "代理人"
name = "「休心沐月」"
start = 2024-11-06T11:00:00
end = 2024-11-27T11:59:59
describe = "[柳(异常·电)]、[安比(击破·电)]、[比利(强攻·物理)]"

[[wish]]
type = "音擎"
name = "「喧哗奏鸣」"
start = 2024-11-06T11:00:00
end = 2024-11-27T11:59:59
describe = "[时流贤者(异常)]、[德玛拉电池Ⅱ型(击破)]、[仿制星徽引擎(强攻)]"

[[wish]]
type = "代理人"
name = "「余烬之冕」"
start = 2024-11-27T12:00:00
end = 2024-12-17T14:59:59
describe = "[莱特(击破·火)]、[本(防护·火)]、[可琳(强攻·物理)]"

[[wish]]
type = "音擎"
name = "「喧哗奏鸣」"
start = 2024-11-27T12:00:00
end = 2024-12-17T14:59:59
describe = "[焰心桂冠(击破)]、[比格气缸(防护)]、[家政员(强攻)]"

[[event]]
type = "活动"
name = "「断层之谜」活动"
start = 2024-11-06T11:00:00
end = 2024-12-17T03:59:59
describe = "达成活动参与条件后可以在斯科特哨站体验「琶音大断层」。"

[[event]]
type = "活动"
name = "「月痕流光」活动"
start = 2024-11-06T11:00:00
end = 2024-12-16T03:59:59
describe = "活动期间，可以在影像档案架旁的电视机处参与「专题放映」活动，使用活动代币兑换并获得限时奖励。部分活动内容将在指定的时间点解锁。"

[[event]]
type = "活动"
name = "「全新放送」活动"
start = 2024-11-06T11:00:00
end = 2024-12-17T03:59:59
describe = "「全新放送」活动期间，累计登录7天即可获得[加密母带]*10！"

[[event]]
type = "活动"
name = "「电子战场乱斗」活动"
start = 2024-11-11T10:00:00
end = 2024-11-25T03:59:59
describe = "活动期间，绳匠可以与录像店中的咔嚓仔对话，并前往HIA俱乐部寻找莱娅，参与全新的VR挑战关卡。"

[[event]]
type = "活动"
name = "「『嗯呢』助教计划」活动"
start = 2024-11-16T10:00:00
end = 2024-12-02T03:59:59
describe = "找到分身乏术的[阿星教练]，担任临时邦布助教，帮它完成毕业生回访和课程训练监督任务吧！"

[[event]]
type = "活动"
name = "「数据悬赏-实战模拟」活动"
start = 2024-11-22T04:00:00
end = 2024-11-27T03:59:59
describe = "「数据悬赏-实战模拟」活动期间，绳匠进入「实战模拟室」，选择任意怪物卡并成功通过挑战，即可获得双倍奖励！"

[[event]]
type = "活动"
name = "「常胜冠军」活动"
start = 2024-11-27T12:00:00
end = 2024-12-16T03:59:59
describe = "活动期间，可以在影像档案架旁的电视机处参与「专题放映」活动，使用活动代币兑换并获得限时奖励。部分活动内容将在指定的时间点解锁。"


[[event]]
type = "活动"
name = "「『嗯呢』从天降」活动"
start = 2024-11-27T10:00:00
end = 2024-12-17T03:59:59
describe = "「『嗯呢』从天降」活动期间，累计登录7天即可获得[邦布券]*10！"

[[event]]
type = "活动"
name = "「帮帮凯伊」活动"
start = 2024-12-02T04:00:00
end = 2024-12-16T03:59:59
describe = "「帮帮凯伊」活动期间，绳匠可与邦布凯伊对话，查看活动任务；完成对应活动任务，即可获得[菲林]、[邦布券]和养成材料等奖励。"

[[event]]
type = "活动"
name = "「当三明治来敲门」活动"
start = 2024-12-04T10:00:00
end = 2024-12-16T03:59:59
describe = "活动期间，绳匠可以在光映广场的三明治餐车领取委托，根据要求为[主厨]选中的幸运顾客们提供服务；完成对应的点单、送餐、合影等任务，并收到来自幸运顾客的评价后，即可获得活动奖励。"

[[event]]
type = "活动"
name = "「先遣赏金-定期清剿」活动"
start = 2024-12-11T04:00:00
end = 2024-12-16T03:59:59
describe = "「先遣赏金-定期清剿」活动期间，绳匠进入「定期清剿」，挑战并通过任意关卡即可获得双倍奖励！"




