name = "星流霆击"
version = "1.4"
special_program = 2024-12-06T19:30:00
update_time = 2024-12-18T06:00:00
wish_name = "调频"

[[wish]]
type = "代理人"
name = "「砺世澄沧」"
start = 2024-12-18T11:00:00
end = 2025-01-21T14:59:59
describe = "[星见雅(异常·烈霜)]、[派派(异常·物理)]、[苍角(支援·冰)]"

[[wish]]
type = "音擎"
name = "「喧哗奏鸣」"
start = 2024-12-18T11:00:00
end = 2025-01-21T14:59:59
describe = "[霰落星殿(异常)]、[轰鸣座驾(异常)]、[含羞恶面(支援)]"

[[wish]]
type = "代理人"
name = "「循此苦旅」"
start = 2024-12-18T11:00:00
end = 2025-01-21T14:59:59
describe = "[浅羽悠真(强攻·电)]、[露西(支援·火)]、[赛斯(防护·电)]"

[[wish]]
type = "音擎"
name = "「灿烂和声」"
start = 2024-12-18T11:00:00
end = 2025-01-21T14:59:59
describe = "[残心青囊(强攻)]、[好斗的阿炮(支援)]、[维序者·特化型(防护)]"

[[event]]
type = "活动"
name = "「特别访客」活动"
start = 2024-12-18T11:00:00
end = 2025-03-12T05:59:59
describe = "「特别访客」活动期间，登录即可获取限定S级代理人[浅羽悠真]，并同时获取可提升代理人至40级的养成补给！"

[[event]]
type = "活动"
name = "「BFF友谊麦岁！」活动"
start = 2024-12-18T11:00:00
end = 2025-01-21T03:59:59
describe = "活动期间，绳匠可以在光映广场的麦当劳餐车和麦小布对话，并帮助狡兔屋的各位代理人完成对应的点餐、送餐等任务。"

[[event]]
type = "活动"
name = "「全新放送」活动"
start = 2024-12-18T11:00:00
end = 2025-01-21T03:59:59
describe = "「全新放送」活动期间，累计登录7天即可获得[加密母带]*10！"

[[event]]
type = "活动"
name = "「小邦布大战坏以骸」活动"
start = 2024-12-20T10:00:00
end = 2025-01-20T03:59:59
describe = "活动期间，绳匠可以在热望角找到阿星教练，帮助它引导小邦布们在不同关卡中战胜以骸，完成考核。"

[[event]]
type = "活动"
name = "「星芒闪耀之处」活动"
start = 2024-12-23T10:00:00
end = 2025-01-06T03:59:59
describe = "活动期间，绳匠可以在热望角和HIA特别活动组的工作人员对话，并在对空六课应援活动中完成主题问答、邀请代理人帮助进行协作宣传。"

[[event]]
type = "活动"
name = "「数据悬赏-实战模拟」活动"
start = 2024-12-25T04:00:00
end = 2024-12-30T03:59:59
describe = "「数据悬赏-实战模拟」活动期间，绳匠进入「实战模拟室」，选择任意怪物卡并成功通过挑战，即可获得双倍奖励！"

[[event]]
type = "活动"
name = "「直到苍白荒秽之地」活动"
start = 2024-12-27T10:00:00
end = 2025-01-20T03:59:59
describe = "与空洞相伴的都市生活，新的麻烦总是一桩又一桩：「曜变之核」出现在特异空洞「墨利诺厄」的天空中，而「法厄同」将再次作为外援协助六课执行官们的行动，前往苍白荒秽之地祓除灾祸。"

[[event]]
type = "活动"
name = "「轻羽逐风」活动"
start = 2024-12-30T10:00:00
end = 2025-01-20T03:59:59
describe = "活动期间，可以在影像档案架旁的电视机处参与活动，使用活动代币兑换并获得限时奖励。部分活动内容将在指定的时间点解锁。"

[[event]]
type = "活动"
name = "「『嗯呢』从天降」活动"
start = 2025-01-01T10:00:00
end = 2025-01-21T03:59:59
describe = "「『嗯呢』从天降」活动期间，累计登录7天即可获得[邦布券]*10！"

[[event]]
type = "活动"
name = "「作战影像回顾」活动"
start = 2025-01-03T10:00:00
end = 2025-01-13T03:59:59
describe = "莱安探员和塔莉调查员打乱了一些图像，它们正需要绳匠的帮助！"

[[event]]
type = "活动"
name = "「协作设计师」活动"
start = 2025-01-09T10:00:00
end = 2025-01-20T03:59:59
describe = "HIA的VR战斗关卡设计师西比尔正在俱乐部分发问卷；独立调查员们可以完成对应战斗、填写问卷，或者帮助西比尔邀请其他人完成问卷，领取她准备的奖励。"

[[event]]
type = "活动"
name = "「帷幕将启之时」活动"
start = 2025-01-13T10:00:00
end = 2025-01-29T03:59:59
describe = "活动期间，累计登录7天即可获得[菲林]*480！"

[[event]]
type = "活动"
name = "「先遣赏金-定期清剿」活动"
start = 2025-01-15T04:00:00
end = 2025-01-20T03:59:59
describe = "「先遣赏金-定期清剿」活动期间，绳匠进入「定期清剿」，挑战并通过任意关卡即可获得双倍奖励！"




