name = "闪耀的此刻"
version = "1.5"
special_program = 2025-01-10T19:30:00
update_time = 2025-01-22T06:00:00
wish_name = "调频"

[[wish]]
type = "代理人"
name = "「千千阙音」「慵懒逐浪」"
start = 2025-01-22T06:00:00
end = 2025-02-12T11:59:59
describe = "[耀嘉音(支援 · 以太)]、[艾莲(强攻 · 冰)]、[安比(击破 · 电)]、[可琳(强攻 · 物理)]"

[[wish]]
type = "音频"
name = "「喧哗奏鸣」「灿烂和声」"
start = 2025-01-22T06:00:00
end = 2025-02-12T11:59:59
describe = "[玲珑妆匣(支援)]、[深海访客(强攻)]、[德玛拉电池Ⅱ型(击破)]、[家政员(强攻)]"

[[wish]]
type = "代理人"
name = "「光与影的纱网」「青如玉壶冰」"
start = 2025-02-12T12:00:00
end = 2025-03-11T14:59:59
describe = "[伊芙琳(强攻 · 火)]、[青衣(击破 · 电)]、[安东(强攻 · 电)]、[妮可(支援 · 以太)]"

[[wish]]
type = "音频"
name = "「喧哗奏鸣」「灿烂和声」"
start = 2025-02-12T12:00:00
end = 2025-03-11T14:59:59
describe = "[心弦夜响(强攻)]、[玉壶青冰(击破)]、[旋钻机-赤轴(强攻)]、[聚宝箱(支援)]"

[[event]]
type = "活动"
name = "「协律共契」活动"
start = 2025-01-22T11:00:00
end = 2025-03-10T03:59:59
describe = "以歌声为引，唤醒灵魂的共鸣。\n活动期间，可以在「Random Play」工作间内的电视机处参与活动；部分活动内容将在指定的时间点解锁。"

[[event]]
type = "活动"
name = "「鲨鲨艾莲之烦恼」活动"
start = 2025-01-22T11:00:00
end = 2025-03-10T03:59:59
describe = "同伴们交换的秘密，编织成温柔的网，包裹住害怕失去的她。\n活动期间，可以在「Random Play」工作间内的电视机处参与活动；部分活动内容将在指定的时间点解锁。"

[[event]]
type = "活动"
name = "「如愿璀璨之日」活动"
start = 2025-01-23T10:00:00
end = 2025-03-10T03:59:59
describe = "活动期间，绳匠可以与耀嘉音一同前往星环参与「丽都有布」大赛，指导伊埃斯完成赛事赛程；赛程进度将随活动阶段逐步解锁。"

[[event]]
type = "活动"
name = "「璀璨序曲」活动"
start = 2025-01-22T11:00:00
end = 2025-03-11T03:59:59
describe = "「璀璨序曲」活动期间，累计登录7天即可获得[加密母带]*10！"

[[event]]
type = "活动"
name = "「美梦如约而至」活动"
start = 2025-01-24T10:00:00
end = 2025-02-05T03:59:59
describe = "约定的聚餐近在眼前，突发全员爽约危机！好消息，您只需付出一点点额外电费，即可消除烦恼。帮助 Fairy 赚取电费，解决朋友们的烦恼，守护期盼已久的聚餐吧。"

[[event]]
type = "活动"
name = "「决战『金手指』之巅」活动"
start = 2025-01-28T10:00:00
end = 2025-02-10T03:59:59
describe = "活动期间，绳匠在六分街的「金手指」电玩店参与活动，每日挑战街机小游戏、完成限时任务，即可获得[电玩节兑换券]；使用[电玩节兑换券]可在限时商店内兑换奖励。"

[[event]]
type = "活动"
name = "「贺岁嘉仪」活动"
start = 2025-01-29T10:00:00
end = 2025-03-11T03:59:59
describe = "「贺岁嘉仪」活动期间，累计登录7天即可获得[加密母带]*10！"

[[event]]
type = "活动"
name = "「咔嚓咔嚓空洞记者」活动"
start = 2025-02-02T10:00:00
end = 2025-02-17T03:59:59
describe = "在所有活动关卡中，绳匠可在合适的时机使用「灵光一闪」技能以获得关卡专属的滤镜增益效果，并释放[能量冲击]对敌人造成伤害。\n活动期间，每日将会开放1个新的活动关卡。完成每个活动关卡后，将会开放对应关卡的「专注拍摄」模式。在「专注拍摄」模式中没有挑战目标的限制，绳匠可以尽情拍摄精彩的战斗瞬间。"

[[event]]
type = "活动"
name = "「先遣赏金-定期清剿」活动"
start = 2025-02-07T04:00:00
end = 2025-02-12T03:59:59
describe = "「先遣赏金-定期清剿」活动期间，绳匠进入「定期清剿」，挑战并通过任意关卡即可获得双倍奖励！"

[[event]]
type = "活动"
name = "「『嗯呢』从天降」活动"
start = 2025-02-12T10:00:00
end = 2025-03-11T03:59:59
describe = "「『嗯呢』从天降」活动期间，累计登录7天即可获得[邦布券]*10！"

[[event]]
type = "活动"
name = "「厄匹斯极钓大师赛」活动"
start = 2025-02-14T10:00:00
end = 2025-03-10T03:59:59
describe = "完成活动期间的限时奖励任务，即可获得活动专属奖励[动态壁纸·邦布钓友会]、[调律校音器]、[菲林]和各类养成材料奖励。"

[[event]]
type = "活动"
name = "「零号空洞：灾兆肃尽」活动"
start = 2025-02-17T10:00:00
end = 2025-03-03T03:59:59
describe = "活动期间，可参与全新玩法「祸首歼灭战」，为代理人配备独特的武备、鸣徽以及「战术强化」，攻克强敌。完成关卡挑战并达到指定评级，即可获得[菲林]和各类养成材料奖励。"

[[event]]
type = "活动"
name = "「本日推荐影片」活动"
start = 2025-02-21T10:00:00
end = 2025-03-03T03:59:59
describe = "活动期间，绳匠可以前往热望角的「Random Play」宣传摊位，找到赫蒂，开启录像带宣传。"

[[event]]
type = "活动"
name = "「『141』环保计划」活动"
start = 2025-02-26T10:00:00
end = 2025-03-10T03:59:59
describe = "活动期间，绳匠每日首次消耗电量，可以获得[废弃电池]；把[废弃电池]交给丝琪，即可兑换[菲林]、[邦布券]和各类养成材料奖励。"

[[event]]
type = "活动"
name = "「数据悬赏-实战模拟」活动"
start = 2025-03-05T04:00:00
end = 2025-03-10T03:59:59
describe = "「数据悬赏-实战模拟」活动期间，绳匠进入「实战模拟室」，选择任意怪物卡并成功通过挑战，即可获得双倍奖励！"
