name = "在被遗忘的废墟之上"
version = "1.6"
special_program = 2025-02-28T19:30:00
update_time = 2025-03-12T06:00:00
wish_name = "调频"

[[wish]]
type = "代理人"
name = "「露电倒影」「天生丽炽」"
start = 2025-03-12T11:00:00
end = 2025-04-02T11:59:59
describe = "[零号·安比(强攻 · 电)]、[柏妮思(异常 · 火)]、[波可娜(击破 · 物理)]、[本(防护 · 火)]"

[[wish]]
type = "音频"
name = "「喧哗奏鸣」「激荡谐振」"
start = 2025-03-12T11:00:00
end = 2025-04-02T11:59:59
describe = "[牺牲洁纯(强攻)]、[灼心摇壶(异常)]、[裁纸刀(击破)]、[比格气缸(防护)]"

[[event]]
type = "活动"
name = "「全新放送」活动"
start = 2025-03-12T11:00:00
end = 2025-04-22T03:59:59
describe = "「全新放送」活动期间，累计登录7天即可获得[加密母带]*10！"

[[event]]
type = "活动"
name = "「银心锡兵之歌」活动"
start = 2025-03-12T11:00:00
end = 2025-04-21T03:59:59
describe = "活动期间，可以在「Random Play」工作间内的电视机处参与活动；部分活动内容将在指定的时间点解锁。"

[[event]]
type = "活动"
name = "「战斗吧！三尺英雄」活动"
start = 2025-03-12T11:00:00
end = 2025-04-21T03:59:59
describe = "活动期间，绳匠可以前往HIA俱乐部跟凯莉对话，并进入观测布塔莉的幻想空间，完成邦布之梦关卡。"
