name = "将眼泪与过往一同埋葬"
version = "1.7"
special_program = 2025-04-11T19:30:00
update_time = 2025-04-23T06:00:00
wish_name = "调频"

[[wish]]
type = "代理人"
name = "「飞鸟坠入良夜」「『查无此人』」"
start = 2025-04-23T11:00:00
end = 2025-05-14T11:59:59
describe = "[薇薇安(异常·以太)]、[简(异常·物理)]、[派派(异常·物理)]、[波赛斯(防护·电)]"

[[wish]]
type = "音频"
name = "「喧哗奏鸣」「激荡谐振」"
start = 2025-04-23T11:00:00
end = 2025-05-14T11:59:59
describe = "[飞鸟星梦(异常)]、[淬锋钳刺(异常)]、[轰鸣座驾(异常)]、[维序者-特化型(防护)]"

[[event]]
type = "活动"
name = "「花语未明之言」活动"
start = 2025-04-23T11:00:00
end = 2025-06-05T03:59:59
describe = "达成参与条件并完成前置委托后，可以在光映广场的「朝露」花店与兰交互，参与「花语未明之言」活动。"

[[event]]
type = "活动"
name = "「全新放送」活动"
start = 2025-04-23T11:00:00
end = 2025-06-05T03:59:59
describe = "「全新放送」活动期间，累计登录7天即可获得[加密母带]*10！"

[[event]]
type = "活动"
name = "「邦邦冲冲冲」活动"
start = 2025-04-27T10:00:00
end = 2025-05-12T03:59:59
describe = "活动期间，绳匠可以前往六分街的阿奇教练处参与活动。"

[[event]]
type = "活动"
name = "「美味食光全城热配」活动"
start = 2025-05-02T10:00:00
end = 2025-05-19T03:59:59
describe = "活动期间，绳匠可以在光映广场的「信仰三明治」餐车领取委托，根据要求为[主厨]选中的幸运顾客们提供服务；完成对应的点单、送餐、合影等任务，并收到来自幸运顾客的评价后，即可获得活动奖励。"

[[event]]
type = "活动"
name = "「先遣赏金-定期清剿」活动"
start = 2025-05-07T04:00:00
end = 2025-05-12T03:59:59
describe = "「先遣赏金-定期清剿」活动期间，绳匠进入「定期清剿」，挑战并通过任意关卡即可获得双倍奖励！"
