name = "荣花与炎日之途"
version = "5.0"
special_program = 2024-08-16T12:00:00
update_time = 2024-08-28T06:00:00
wish_name = "祈愿"

[[wish]]
type = "角色"
name = "「鲨鲨逐浪游」&「叶落风随」"
start = 2024-08-28T11:00:00
end = 2024-09-17T17:59:59
describe = "玛拉妮&枫原万叶"

[[wish]]
type = "武器"
name = "「法器·冲浪时光」&「单手剑·苍古自由之誓」"
start = 2024-08-28T11:00:00
end = 2024-09-17T17:59:59
describe = "「法器·冲浪时光」&「单手剑·苍古自由之誓」"

[[wish]]
type = "角色"
name = "「巡火猎秘」&「影寂天下人」"
start = 2024-09-17T18:00:00
end = 2024-10-08T14:59:59
describe = "基尼奇&雷电将军"

[[wish]]
type = "武器"
name = "「双手剑·山王长牙」&「长柄武器·薙草之稻光」"
start = 2024-09-17T18:00:00
end = 2024-10-08T14:59:59
describe = "「双手剑·山王长牙」&「长柄武器·薙草之稻光」"

[[event]]
type = "任务限时奖励"
name = "「荣花与炎日之途」时限内完成魔神任务，可额外获得原石*500"
start = 2024-08-28T11:00:00
end = 2024-10-08T14:59:59
describe = "在时限内完成相应魔神任务，可获得额外奖励：原石*500。"

[[event]]
type = "任务限时奖励"
name = "「尤潘基的回火」时限内完成部族纪闻任务，可额外获得原石等奖励"
start = 2024-09-17T18:00:00
end = 2024-10-08T14:59:59
describe = "在时限内完成任务，可额外获得原石、角色突破素材、角色培养素材、纳塔区域特产等奖励。"

[[event]]
type = "任务限时奖励"
name = "「流泉所归之处」时限内完成部族纪闻任务，可额外获得原石等奖励"
start = 2024-08-28T11:00:00
end = 2024-09-17T17:59:59
describe = "在时限内完成任务，可额外获得原石、角色突破素材、角色培养素材、纳塔区域特产等奖励。"

[[event]]
type = "七圣召唤"
name = "「七圣召唤」铸境研炼：奕思巧战"
start = 2024-10-19T10:00:00
end = 2024-11-04T03:59:59
describe = "活动开启后，旅行者可前往猫尾酒馆的小王子处选择关卡进行挑战。"

[[event]]
type = "七圣召唤"
name = "「七圣召唤」热斗模式：奇策竞驰"
start = 2024-09-07T10:00:00
end = 2024-09-23T03:59:59
describe = "活动开启后，旅行者可前往猫尾酒馆的邀请板处，参与「热斗模式」特殊规则下的「七圣召唤」对局。"

[[event]]
type = "活动"
name = "「行步诸野，寻燎故焰」：自选邀约「奔行世间」常驻祈愿5星角色"
start = 2024-08-28T11:00:00
end = 2024-10-08T14:59:59
describe = "活动期间，旅行者可通过活动界面自选邀约一名「奔行世间」常驻祈愿5星角色加入队伍！"

[[event]]
type = "活动"
name = "「绮绘的踪绪」活动：参与获得活动专属武器「法器·苍纹角杯」"
start = 2024-08-28T11:00:00
end = 2024-09-16T03:59:59
describe = "活动期间，可在回声之子、流泉之众、悬木人三个部族所在地区探寻灵感，开启「奔流真形」「迸烈极态」「本貌明彩」等灵感收集挑战。"

[[event]]
type = "活动"
name = "「瑞彩流虹」累计登录七天获得纠缠之缘*10"
start = 2024-08-30T04:00:00
end = 2024-09-18T03:59:59
describe = "活动期间，累计登录七天即可获得纠缠之缘*10等奖励！"

[[event]]
type = "活动"
name = "「嘟嘟可砰砰历险记」活动：奇趣炸鱼挑战"
start = 2024-09-09T10:00:00
end = 2024-09-23T03:59:59
describe = "指挥嘟嘟可放置炸弹，并将其引爆，击退所有角角鱼敌人，赢取物资奖励！"

[[event]]
type = "活动"
name = "「地脉移涌」活动"
start = 2024-09-16T04:00:00
end = 2024-09-23T03:59:59
describe = "「藏金之花」「启示之花」双倍掉落！"

[[event]]
type = "活动"
name = "「荆棘与勋冠」活动"
start = 2024-09-20T10:00:00
end = 2024-09-30T03:59:59
describe = "获取增益，击败敌人"

[[event]]
type = "活动"
name = "「提瓦特忆画」活动"
start = 2024-09-28T10:00:00
end = 2024-10-08T03:59:59
describe = "回忆留影之旅"

[[event]]
type = "活动"
name = "「新途绮礼」感恩答谢"
start = 2024-09-28T00:00:00
end = 2024-10-09T04:00:00
describe = "登录领取1600原石、祝圣之霜等奖励"


