name = "命定将焚的虹光"
version = "5.1"
special_program = 2024-09-27T20:00:00
update_time = 2024-10-09T06:00:00
wish_name = "祈愿"

[[wish]]
type = "角色"
name = "「煅火的祝赐」&「千云绘羽织」"
start = 2024-10-09T11:00:00
end = 2024-10-29T17:59:59
describe = "希诺宁&千织"

[[wish]]
type = "武器"
name = "「单手剑·岩峰巡歌」&「单手剑·有乐御簾切」"
start = 2024-10-09T11:00:00
end = 2024-10-29T17:59:59
describe = "「单手剑·岩峰巡歌」&「单手剑·有乐御簾切」"

[[wish]]
type = "角色"
name = "「月草的赐慧」&「赤团开时」"
start = 2024-10-29T18:00:00
end = 2024-11-19T14:59:59
describe = "纳西妲&胡桃"

[[wish]]
type = "武器"
name = "「法器·千夜浮梦」&「长柄武器·护摩之杖」"
start = 2024-10-29T18:00:00
end = 2024-11-19T14:59:59
describe = "「法器·千夜浮梦」&「长柄武器·护摩之杖」"

[[event]]
type = "任务限时奖励"
name = "「命定将焚的虹光」时限内完成魔神任务，可额外获得原石奖励"
start = 2024-10-09T11:00:00
end = 2024-11-19T14:59:59
describe = "在时限内完成相应魔神任务，可获得额外奖励：原石*500。"

[[event]]
type = "任务限时奖励"
name = "「祈祝福愿，倾告嵴锋」时限内完成部族纪闻任务，可额外获得奖励"
start = 2024-10-09T11:00:00
end = 2024-10-29T17:59:59
describe = "在时限内完成任务，可额外获得原石、角色突破素材、角色培养素材、纳塔区域特产等奖励。"

[[event]]
type = "任务限时奖励"
name = "「彩石与焰泉之国」时限内完成探索任务，可额外获得原石奖励"
start = 2024-10-09T11:00:00
end = 2024-12-31T14:59:59
describe = "在时限内完成相应探索任务，可获得额外奖励：原石*400。"

[[event]]
type = "七圣召唤"
name = "「七圣召唤」热斗模式：列阵斗巧"
start = 2024-10-19T10:00:00
end = 2024-11-04T03:59:59
describe = "活动开启后，旅行者可前往猫尾酒馆的邀请板处，参与「热斗模式」特殊规则下的「七圣召唤」对局。"

[[event]]
type = "活动"
name = "「寻溯蜜虫之宝」活动"
start = 2024-10-10T10:00:00
end = 2024-10-21T03:59:59
describe = "活动开始后的前五天，每天会开启一个新的挑战。挑战中，旅行者需要寻找并追击被深渊力量侵蚀的燃素蜜虫，灵活使用「捕虫网」破除其护罩，在规定时间内削减深渊力量，捕捉蜜虫。完成指定目标可获得原石、武器突破素材、祝圣油膏、精锻用魔矿、摩拉奖励。"

[[event]]
type = "活动"
name = "追想练行·烈趣篇"
start = 2024-10-17T10:00:00
end = 2024-10-28T03:59:59
describe = "活动期间，旅行者可通过单人匹配或队伍匹配的方式参与玩法，随机挑战4个关卡，并根据关卡和「追想支援」选择适合角色与「追想助益」，完成不同的「练行项目」目标，获取「烈趣之星」奖励。累计获得指定数量的「烈趣之星」即可领取原石、大英雄的经验、角色天赋素材等奖励。"

[[event]]
type = "活动"
name = "「彩糖与蔷薇的幻色颂」活动"
start = 2024-10-23T10:00:00
end = 2024-11-07T03:59:59
describe = "活动期间，将陆续解锁「花车摇曳」、「交映现实与梦」、「骑士的剑影」各阶段玩法。完成挑战后，可获得「庆典热度」。累计获取指定数量的「庆典热度」即可邀请「浮金的誓愿·坎蒂丝(水)」，还可获得原石、智识之冕等奖励。"

[[event]]
type = "活动"
name = "「攻逐飨会」活动"
start = 2024-11-01T10:00:00
end = 2024-11-15T03:59:59
describe = "活动开始后的前六天，每天会开启一个新的挑战。"

[[event]]
type = "活动"
name = "「百货奇货」活动"
start = 2024-11-11T10:00:00
end = 2024-11-18T03:59:59
describe = "开奇货匣得原石"
