name = "灵与火的织卷"
version = "5.2"
special_program = 2024-11-08T20:00:00
update_time = 2024-11-20T06:00:00
wish_name = "祈愿"

[[wish]]
type = "角色"
name = "「饮羽散红」&「光与影的戏术」"
start = 2024-11-20T11:00:00
end = 2024-12-10T17:59:59
describe = "恰斯卡&林尼"

[[wish]]
type = "武器"
name = "「弓·星鹫赤羽」&「弓·最初的大魔术」"
start = 2024-11-20T11:00:00
end = 2024-12-10T17:59:59
describe = "「弓·星鹫赤羽」&「弓·最初的大魔术」"

[[wish]]
type = "角色"
name = "「渊海界令」&「陵薮市朝」"
start = 2024-12-10T18:00:00
end = 2024-12-31T14:59:59
describe = "那维莱特&钟离"

[[wish]]
type = "武器"
name = "「法器·万世流涌大典」&「长柄武器·贯虹之槊」"
start = 2024-12-10T18:00:00
end = 2024-12-31T14:59:59
describe = "「法器·万世流涌大典」&「长柄武器·贯虹之槊」"

[[event]]
type = "任务限时奖励"
name = "「花之归尘，羽之将坠」时限内完成部族纪闻任务，可额外获得奖励"
start = 2024-11-20T11:00:00
end = 2024-12-10T17:59:59
describe = "在时限内完成任务，可额外获得原石、角色突破素材、角色培养素材、纳塔区域特产等奖励。"

[[event]]
type = "任务限时奖励"
name = "「朝向领风之崖与流灰之都」时限内完成探索任务，可额外获得原石奖励"
start = 2024-11-20T11:00:00
end = 2025-02-11T14:59:59
describe = "在时限内完成相应探索任务，可获得额外奖励：原石*400。"

[[event]]
type = "七圣召唤"
name = "「七圣召唤」热斗模式：自行巧局"
start = 2024-11-22T10:00:00
end = 2024-12-16T03:59:59
describe = "活动开启后，旅行者可前往猫尾酒馆的邀请板处，参与「热斗模式」特殊规则下的「七圣召唤」对局。"

[[event]]
type = "七圣召唤"
name = "「七圣召唤」铸境研炼：无量疾战"
start = 2024-11-20T11:00:00
end = 2025-01-01T06:00:00
describe = "活动开启后，旅行者可前往猫尾酒馆的小王子处选择关卡进行挑战。"

[[event]]
type = "活动"
name = "「暝视寻灵织卷」活动"
start = 2024-11-28T10:00:00
end = 2024-12-16T03:59:59
describe = "「暝视寻灵织卷」活动"

[[event]]
type = "活动"
name = "「伴爪同行」活动"
start = 2024-11-22T10:00:00
end = 2024-12-02T03:59:59
describe = "寻找小动物挑战"

[[event]]
type = "活动"
name = "「冒险家试炼·蜕变篇」活动"
start = 2024-12-11T10:00:00
end = 2024-12-23T03:59:59
describe = "活动开启后的前四天，每天都会解锁新的「全能试炼」。每个「全能试炼」中，旅行者需要连续完成三个挑战关卡。每个关卡需要使用指定的试用角色，在限定时间内达成挑战目标。"

[[event]]
type = "活动"
name = "「强风猛进之述演」活动"
start = 2024-12-18T10:00:00
end = 2024-12-30T03:59:59
describe = "在「强风猛进之述演」活动中，旅行者每个回合都会获得一定数量的交战单位和战斗策略。选取合适的交战单位和战斗策略，分析对手和自己的阵容，安排合理的出战单位，方可克敌制胜。"

[[event]]
type = "活动"
name = "「地脉移涌」活动"
start = 2024-12-23T04:00:00
end = 2024-12-30T03:59:59
describe = "「地脉移涌」活动期间，旅行者成功挑战「地脉衍出·藏金之花」或「地脉衍出·启示之花」领取秘宝奖励时，消耗「原粹树脂」可获得双倍奖励，每天一共可享受3次双倍掉落机会！"

