name = "炽烈的还魂诗"
version = "5.3"
special_program = 2024-12-20T20:00:00
update_time = 2025-01-01T06:00:00
wish_name = "祈愿"

[[wish]]
type = "角色"
name = "「宿古的赫炎」&「星边夜语」"
start = 2025-01-01T11:00:00
end = 2025-01-21T17:59:59
describe = "玛薇卡&茜特菈莉"

[[wish]]
type = "武器"
name = "「双手剑·焚曜千阳」&「法器·祭星者之望」"
start = 2025-01-01T11:00:00
end = 2025-01-21T17:59:59
describe = "「双手剑·焚曜千阳」&「法器·祭星者之望」"

[[wish]]
type = "角色"
name = "「炉边烬影」&「流霆贯夜」"
start = 2025-01-21T18:00:00
end = 2025-02-11T14:59:59
describe = "阿蕾奇诺&克洛琳德"

[[wish]]
type = "武器"
name = "「长柄武器·赤月之形」&「单手剑·赦罪」"
start = 2025-01-21T18:00:00
end = 2025-02-11T14:59:59
describe = "「长柄武器·赤月之形」&「单手剑·赦罪」"

[[wish]]
type = "集录"
name = "「玉岩之忆」"
start = 2025-01-21T18:00:00
end = 2025-02-11T14:59:59
describe = "活动期间，旅行者可以在本期所有5星物品中自主选择并定轨1个5星角色或1个5星武器作为本期「玉岩之忆」祈愿出现概率提升的5星物品！"

[[event]]
type = "任务限时奖励"
name = "「正如那烈日」时限内完成传说任务，可额外获得原石等奖励"
start = 2025-01-01T11:00:00
end = 2025-01-21T17:59:59
describe = "在时限内完成任务，可额外获得原石、角色突破素材、角色培养素材、纳塔区域特产等奖励。"

[[event]]
type = "任务限时奖励"
name = "「流淌着色彩的回忆」时限内完成部族纪闻任务，可额外获得奖励"
start = 2025-01-01T11:00:00
end = 2025-01-21T17:59:59
describe = "在时限内完成任务，可额外获得原石、角色突破素材、角色培养素材、纳塔区域特产等奖励。"

[[event]]
type = "任务限时奖励"
name = "「炽烈的还魂诗」时限内完成魔神任务，可额外获得原石奖励"
start = 2025-01-01T11:00:00
end = 2025-02-11T14:59:59
describe = "在时限内完成相应魔神任务，可获得额外奖励：原石*500。"

[[event]]
type = "衣装限时折扣"
name = "「宿雪桃红」衣装限时折扣"   #「宿雪桃红」衣装限时折扣
start = 2025-01-01T11:00:00
end = 2025-02-10T03:59:59
describe = "折扣期间衣装售价为1350创世结晶，限时折扣结束后价格将恢复至1680创世结晶，上架期间限购1次。"

[[event]]
type = "七圣召唤"
name = "「七圣召唤」铸境研炼：奕思巧战"    #「七圣召唤」铸境研炼：奕思巧战
start = 2025-01-01T11:00:00
end = 2025-02-12T03:59:59
describe = "本次活动包含4个关卡，部分关卡有不同的特殊胜利或失败条件。每个关卡存在与胜利或失败条件相关的特殊规则。"

[[event]]
type = "七圣召唤"
name = "「七圣召唤」热斗模式：奇策竞驰"
start = 2025-01-01T11:00:00
end = 2025-01-27T03:59:59
describe = "活动开启后，旅行者可前往猫尾酒馆的邀请板处，参与「热斗模式」特殊规则下的「七圣召唤」对局。"

[[event]]
type = "活动"
name = "「漱玉工奇斗虫大玄境」活动"  #「漱玉工奇斗虫大玄境」活动
start = 2025-01-03T10:00:00
end = 2025-01-13T03:59:59
describe = "趣味斗虫挑战；活动开始后，每天都会解锁一个新的挑战关卡，共5关。"

[[event]]
type = "活动"
name = "「衔勇诚砺之证」活动"
start = 2025-01-09T10:00:00
end = 2025-01-20T03:59:59
describe = "活动开始后的第一、三、五天，将分别解锁两个与特定部族有关的新挑战，共六个挑战"

[[event]]
type = "活动"
name = "「凶魁巨怪觇候录」活动"
start = 2025-01-14T10:00:00
end = 2025-01-27T03:59:59
describe = "从活动开始的第一天起，每两天可解锁新的挑战。旅行者可以与赫卡对话，进行不同难度的挑战。"

[[event]]
type = "活动"
name = "「富贵登门·春来早知」活动"
start = 2025-01-22T04:00:00
end = 2025-02-11T14:59:59
describe = "活动期间，将开放「开门迎财·累计登录」与「旧忆新桃·海灯节答谢」奖励。可获取1600原石、纠缠之缘*10、智识之冕、祝圣之霜等奖励。"

[[event]]
type = "活动"
name = "「春曦画桃符」活动"
start = 2025-01-24T10:00:00
end = 2025-02-09T03:59:59
describe = "活动期间，将陆续解锁「八奇乱斗」、「灯下演武」、「如意祝柬」、「节庆旅纪」各阶段玩法。"

[[event]]
type = "活动"
name = "「盛材移涌」活动"
start = 2025-02-03T04:00:00
end = 2025-02-10T03:59:59
describe = "活动期间，成功挑战「精通秘境」或「炼武秘境」，消耗「原粹树脂」领取秘宝奖励时，可获得双倍奖励。"


