name = "梦间见月明"
version = "5.4"
special_program = 2025-01-24T20:00:00
update_time = 2025-02-12T06:00:00
wish_name = "祈愿"

[[wish]]
type = "角色"
name = "「浮枕朝颜」&「柔柔海露心」"
start = 2025-02-12T11:00:00
end = 2025-03-04T17:59:59
describe = "梦见月瑞希&希格雯"

[[wish]]
type = "武器"
name = "「法器·寝正月初晴」&「弓·白雨心弦」"
start = 2025-02-12T11:00:00
end = 2025-03-04T17:59:59
describe = "「法器·寝正月初晴」&「弓·白雨心弦」"

[[wish]]
type = "角色"
name = "「众水的颂诗」&「劫中泛滥」"
start = 2025-03-04T18:00:00
end = 2025-03-25T14:59:59
describe = "芙宁娜&莱欧斯利"

[[wish]]
type = "武器"
name = "「单手剑·静水流涌之辉」&「法器·金流监督」"
start = 2025-03-04T18:00:00
end = 2025-03-25T14:59:59
describe = "「单手剑·静水流涌之辉」&「法器·金流监督」"

[[event]]
type = "任务限时奖励"
name = "「貘枕之章」时限内完成传说任务，可额外获得原石等奖励"
start = 2025-02-12T11:00:00
end = 2025-03-04T17:59:59
describe = "在时限内完成任务，可额外获得原石、角色突破素材、角色培养素材、稻妻区域特产等奖励。"

[[event]]
type = "七圣召唤"
name = "「七圣召唤」铸境研炼：巧策进斗"
start = 2025-02-12T11:00:00
end = 2025-03-26T03:59:59
describe = "活动开启后，旅行者可前往猫尾酒馆的小王子处选择关卡进行挑战。"

[[event]]
type = "七圣召唤"
name = "「七圣召唤」热斗模式：自行巧局"
start = 2025-02-21T10:00:00
end = 2025-03-17T03:59:59
describe = "活动开启后，旅行者可前往猫尾酒馆的邀请板处，参与「热斗模式」特殊规则下的「七圣召唤」对局。"

[[event]]
type = "活动"
name = "「游逸旅闻·诗汇之章」活动：拜访伙伴，闲叙趣闻"
start = 2025-02-12T11:00:00
end = 2025-03-25T14:59:59
describe = "活动期间，旅行者可以在地图上寻找伙伴们，并前往各地进行拜访。听他们闲叙一番平日里的趣闻，或是与他们一同度过闲适的一天。"

[[event]]
type = "活动"
name = "「三川游艺绮梦谭」活动"
start = 2025-02-14T10:00:00
end = 2025-03-03T03:59:59
describe = "活动期间，完成各项挑战可获得「游艺印章」。累计获取指定数量的「游艺印章」即可获得「长柄武器·且住亭御咄」、原石、智识之冕、活动专属武器精炼材料等奖励。"

[[event]]
type = "活动"
name = "「征战勇者淬炼之界」活动"
start = 2025-02-24T10:00:00
end = 2025-03-10T03:59:59
describe = "活动开始后，每天都会解锁一个新的挑战，每个挑战均有25层战斗关卡，30秒内通过即可继续挑战。通过指定层数，可获得原石、角色天赋素材、祝圣油膏等奖励。"

[[event]]
type = "活动"
name = "「异域鱼鱼追渔行动」活动：捕捉入侵鱼类"
start = 2025-03-05T10:00:00
end = 2025-03-17T03:59:59
describe = "活动中，旅行者需要消耗行动点投掷渔网，捕捉各种入侵的鱼类。"

[[event]]
type = "活动"
name = "「剪影辑帧」活动：创意广告剪辑"
start = 2025-03-12T10:00:00
end = 2025-03-24T03:59:59
describe = "旅行者需要根据脚本规划，为每一镜选择合适的素材，组成广告成片并完成剪辑。同一脚本中，同一个素材可至多重复使用3次。"
