name = "众火溯还之日"
version = "5.5"
special_program = 2025-03-14T20:00:00
update_time = 2025-03-26T06:00:00
wish_name = "祈愿"

[[wish]]
type = "角色"
name = "「饫宴角戏」&「云府鹤行」"
start = 2025-03-26T11:00:00
end = 2025-04-15T17:59:59
describe = "瓦雷莎&闲云"

[[wish]]
type = "武器"
name = "「法器·溢彩心念」&「法器·鹤鸣余音」"
start = 2025-03-26T11:00:00
end = 2025-04-15T17:59:59
describe = "「法器·溢彩心念」&「法器·鹤鸣余音」"

[[wish]]
type = "角色"
name = "「煅火的祝赐」&「杯装之诗」"
start = 2025-04-15T18:00:00
end = 2025-05-06T14:59:59
describe = "希诺宁&温迪"

[[wish]]
type = "武器"
name = "「单手剑·岩峰巡歌」&「弓·终末嗟叹之诗」"
start = 2025-04-15T18:00:00
end = 2025-05-06T14:59:59
describe = "「单手剑·岩峰巡歌」&「弓·终末嗟叹之诗」"

[[event]]
type = "任务限时奖励"
name = "「蘑境菌奇」时限内完成部族纪闻任务，可额外获得原石等奖励"
start = 2025-03-26T11:00:00
end = 2025-04-15T17:59:59
describe = "在时限内完成任务，可额外获得原石、角色突破素材、角色培养素材、纳塔区域特产等奖励。"

[[event]]
type = "任务限时奖励"
name = "「圣山所在是安饶之陆」时限内完成探索任务，可额外获得奖励"
start = 2025-03-26T11:00:00
end = 2025-06-17T14:59:59
describe = "在时限内完成相应探索任务，可获得额外奖励：原石*400。"

[[event]]
type = "七圣召唤"
name = "「七圣召唤」铸境研炼：无量疾战"
start = 2025-03-26T11:00:00
end = 2025-05-07T03:59:59                   # 暂定
describe = "活动开启后，旅行者可前往猫尾酒馆的小王子处选择关卡进行挑战。"
