name = "众火溯还之日"
version = "5.5"
special_program = 2025-03-14T20:00:00
update_time = 2025-03-26T06:00:00
wish_name = "祈愿"

[[wish]]
type = "角色"
name = "「饫宴角戏」&「云府鹤行」"
start = 2025-03-26T11:00:00
end = 2025-04-15T17:59:59
describe = "瓦雷莎&闲云"

[[wish]]
type = "武器"
name = "「法器·溢彩心念」&「法器·鹤鸣余音」"
start = 2025-03-26T11:00:00
end = 2025-04-15T17:59:59
describe = "「法器·溢彩心念」&「法器·鹤鸣余音」"

[[wish]]
type = "角色"
name = "「煅火的祝赐」&「杯装之诗」"
start = 2025-04-15T18:00:00
end = 2025-05-06T14:59:59
describe = "希诺宁&温迪"

[[wish]]
type = "武器"
name = "「单手剑·岩峰巡歌」&「弓·终末嗟叹之诗」"
start = 2025-04-15T18:00:00
end = 2025-05-06T14:59:59
describe = "「单手剑·岩峰巡歌」&「弓·终末嗟叹之诗」"

[[event]]
type = "任务限时奖励"
name = "「蘑境菌奇」时限内完成部族纪闻任务，可额外获得原石等奖励"
start = 2025-03-26T11:00:00
end = 2025-04-15T17:59:59
describe = "在时限内完成任务，可额外获得原石、角色突破素材、角色培养素材、纳塔区域特产等奖励。"

[[event]]
type = "任务限时奖励"
name = "「圣山所在是安饶之陆」时限内完成探索任务，可额外获得奖励"
start = 2025-03-26T11:00:00
end = 2025-06-17T14:59:59
describe = "在时限内完成相应探索任务，可获得额外奖励：原石*400。"

[[event]]
type = "七圣召唤"
name = "「七圣召唤」铸境研炼：无量疾战"
start = 2025-03-26T11:00:00
end = 2025-05-07T03:59:59                   # 暂定
describe = "活动开启后，旅行者可前往猫尾酒馆的小王子处选择关卡进行挑战。"

[[event]]
type = "活动"
name = "「荣花竞捷之争」活动：参与邀请「深黯的谜烟·欧洛伦(雷)」"
start = 2025-03-28T10:00:00
end = 2025-04-14T03:59:59
describe = "「荣花演武」中，旅行者可参与六大部族之间的攻防演武，与伙伴们并肩作战，完成各种演武中的目标，攻夺胜利与荣誉。"

[[event]]
type = "七圣召唤"
name = "「七圣召唤」热斗模式：列阵斗巧"
start = 2025-04-05T10:00:00
end = 2025-04-21T03:59:59
describe = "活动开启后，旅行者可前往猫尾酒馆的邀请板处，参与「热斗模式」特殊规则下的「七圣召唤」对局。"

[[event]]
type = "活动"
name = "「无极限超激格斗赛」活动：地下激斗挑战赛"
start = 2025-04-07T10:00:00
end = 2025-04-21T03:59:59
describe = "活动开始后，每天都会解锁一个新的挑战，共5关。挑战分为「上半场」和「下半场」两场战斗。"

[[event]]
type = "活动"
name = "「祝圣移涌」活动：圣遗物双倍掉落"
start = 2025-04-14T04:00:00
end = 2025-04-21T03:59:59
describe = "「祝圣移涌」活动期间，旅行者成功挑战「祝圣秘境」，领取秘宝奖励时，消耗「原粹树脂」可获得双倍奖励，每天一共可享受3次双倍掉落机会！"

[[event]]
type = "活动"
name = "「奇逸角技隆隆擂台」活动：趣味多人挑战"
start = 2025-04-21T10:00:00
end = 2025-05-02T03:59:59
describe = "活动开启后的前3天，每天都会解锁新的试炼。旅行者可通过单人匹配或队伍匹配两种方式游玩已解锁的试炼。"

[[event]]
type = "活动"
name = "「节拍撞球·梅兹特利篇」活动：元素击球挑战"
start = 2025-04-28T10:00:00
end = 2025-05-06T03:59:59
describe = "活动开始后，每天都会解锁一个新的关卡，共6关。旅行者需要移动球板，回击飞来的撞球，击碎各种节奏方块。"
