name = "众火溯还之日"
version = "5.5"
special_program = 2025-03-14T20:00:00
update_time = 2025-03-26T06:00:00
wish_name = "祈愿"

[[wish]]
type = "角色"
name = "「饫宴角戏」&「云府鹤行」"
start = 2025-03-26T11:00:00
end = 2025-04-15T17:59:59
describe = "瓦雷莎&闲云"

[[wish]]
type = "武器"
name = "「法器·溢彩心念」&「法器·鹤鸣余音」"
start = 2025-03-26T11:00:00
end = 2025-04-15T17:59:59
describe = "「法器·溢彩心念」&「法器·鹤鸣余音」"

[[wish]]
type = "角色"
name = "「煅火的祝赐」&「杯装之诗」"
start = 2025-04-15T18:00:00
end = 2025-05-06T14:59:59
describe = "希诺宁&温迪"

[[wish]]
type = "武器"
name = "「单手剑·岩峰巡歌」&「弓·终末嗟叹之诗」"
start = 2025-04-15T18:00:00
end = 2025-05-06T14:59:59
describe = "「单手剑·岩峰巡歌」&「弓·终末嗟叹之诗」"

