name = "悖理"
version = "5.6"
special_program = 2025-04-25T20:00:00
update_time = 2025-05-07T06:00:00
wish_name = "祈愿"

[[wish]]
type = "角色"
name = "「莓色香颂」&「刺玫的铭誓」"
start = 2025-05-07T11:00:00
end = 2025-05-27T17:59:59
describe = "爱可菲&娜维娅"

[[wish]]
type = "武器"
name = "「长柄武器·香韵奏者」&「双手剑·裁断」"
start = 2025-05-07T11:00:00
end = 2025-05-27T17:59:59
describe = "「长柄武器·香韵奏者」&「双手剑·裁断」"

[[event]]
type = "任务限时奖励"
name = "「珍上至珍」时限内完成传说任务，可额外获得原石等奖励"
start = 2025-05-07T11:00:00
end = 2025-05-27T17:59:59
describe = "在时限内完成任务，可额外获得原石、角色突破素材、角色培养素材、枫丹区域特产等奖励。"

[[event]]
type = "七圣召唤"
name = "「七圣召唤」铸境研炼：巧策进斗"
start = 2025-05-07T11:00:00
end = 2025-06-18T03:59:59
describe = "活动开启后，旅行者可前往猫尾酒馆的小王子处选择关卡进行挑战。"

[[event]]
type = "七圣召唤"
name = "「七圣召唤」热斗模式：自行巧局"
start = 2025-05-17T10:00:00
end = 2025-06-02T03:59:59
describe = "活动开启后，旅行者可前往猫尾酒馆的邀请板处，参与「热斗模式」特殊规则下的「七圣召唤」对局。"

[[event]]
type = "活动"
name = "「和旋舞剧」活动：参与获得活动专属武器「弓·冷寂迸音」"
start = 2025-05-09T10:00:00
end = 2025-05-26T03:59:59
describe = "活动期间，旅行者需要经营一座映影主题的乐园「海薇玛映影欢乐城」，乐园中有着三个主要的游乐项目「缤纷蹈险奇行」、「妙影名篇」、「悠悠慢庄园」。"
