name = "明霄竞武试锋芒"
version = "2.4"
special_program = 2024-07-19T19:30:00
update_time = 2024-07-31T06:00:00
wish_name = "活动跃迁"

[[wish]]
type = "角色"
name = "「掷山破云」、「令奉贞凶」"
start = 2024-08-28T11:00:00
end = 2024-09-17T17:59:59
describe = "活动期间，限定5星角色「云璃（毁灭•物理）」，4星角色「寒鸦（同谐•物理）」「驭空（同谐•虚数）」「玲可（丰饶•量子）」跃迁成功概率限时提升。"

[[wish]]
type = "武器"
name = "「法器·冲浪时光」&「单手剑·苍古自由之誓」"
start = 2024-08-28T11:00:00
end = 2024-09-17T17:59:59
describe = "「法器·冲浪时光」&「单手剑·苍古自由之誓」"

[[wish]]
type = "角色"
name = "「巡火猎秘」&「影寂天下人」"
start = 2024-09-17T18:00:00
end = 2024-10-08T14:59:59
describe = "基尼奇&雷电将军"

[[wish]]
type = "武器"
name = "「双手剑·山王长牙」&「长柄武器·薙草之稻光」"
start = 2024-09-17T18:00:00
end = 2024-10-08T14:59:59
describe = "「双手剑·山王长牙」&「长柄武器·薙草之稻光」"
