name = "再创世的凯歌"
version = "3.0"
special_program = 2025-01-01T19:30:00
update_time = 2025-01-15T06:00:00
wish_name = "活动跃迁"

[[wish]]
type = "角色"
name = "「视界来信」「铭心之萃」"
start = 2025-01-15T11:00:00
end = 2025-02-05T11:59:59
describe = "「大黑塔（智识•冰）」「灵砂（丰饶•火）」「飞霄（巡猎•风）」「翡翠（智识•量子）」"

[[wish]]
type = "光锥"
name = "「流光定影」「真意之汇」"
start = 2025-01-15T11:00:00
end = 2025-02-05T11:59:59
describe = "「向着不可追问处（智识）」「唯有香如故（丰饶）」「我将，巡征追猎（巡猎）」「偏偏希望无价（智识）」"

[[wish]]
type = "角色"
name = "「裁酌天命」「铭心之萃」"
start = 2025-02-05T12:00:00
end = 2025-02-25T15:00:00
describe = "「阿格莱雅（记忆•雷）」「波提欧（巡猎•物理）」「知更鸟（同谐•物理）」「银狼（虚无•量子）」"

[[wish]]
type = "光锥"
name = "「流光定影」「真意之汇」"
start = 2025-02-05T12:00:00
end   = 2025-02-25T15:00:00
describe = "「将光阴织成黄金（记忆）」「驶向第二次生命（巡猎）」「夜色流光溢彩（同谐）」「雨一直下（虚无）」"

[[event]]
type = "活动"
name = "「银河潮流指南」活动"
start = 2025-01-15T11:00:00
end   = 2025-02-26T06:00:00
describe = "3.0版本期间登录游戏并解锁「角色」功能后即可领取「三月七•存护」的时装「冬去煦至」！"

[[event]]
type = "活动"
name = "「伊利亚游记」：探索「翁法罗斯」、完成任务，获取星琼等奖励"
start = 2025-01-15T11:00:00
end   = 2025-02-24T03:00:00
describe = "开拓者在「翁法罗斯」完成游记中的指定条目后，即可于相应页面领取奖励。"

[[event]]
type = "活动"
name = "「迷迷赠礼」：登录游戏即可领取星轨专票*10、变量骰子*1！"
start = 2025-01-15T11:00:00
end   = 2025-02-26T06:00:00
describe = "活动期间，登录游戏即可在「旅情事记」-「迷迷赠礼」界面，领取星轨专票*10与变量骰子*1！"

[[event]]
type = "活动"
name = "「地宫迷踪」活动"
start = 2025-01-22T12:00:00
end   = 2025-02-24T03:59:59
describe = "活动开启后，「浅层地宫」的「预言算碑」玩法会开启第一个房间；解开该房间封印后解锁下一个房间，探索该难度下该玩法的全部房间会解锁下一个玩法，以此类推。"

[[event]]
type = "活动"
name = "「银河幸运星」活动"
start = 2025-01-27T04:00:00
end   = 2025-02-26T06:00:00
describe = "开拓者可以在每一期的截止时间前（具体时间以活动界面中的显示为准），选择参与抽奖或直接领取100星琼的固定奖励，仅能选择其中一个选项。每期可选择不同的选项。"

[[event]]
type = "活动"
name = "「位面分裂」活动：位面饰品限时双倍掉落"
start = 2025-01-27T04:00:00
end   = 2025-02-03T03:59:59
describe = "「位面分裂」活动期间，挑战「模拟宇宙」或「差分宇宙」时，可获得双倍奖励。"

[[event]]
type = "活动"
name = "「晨昏卷隐」：击败故事中的对手，获取命运的足迹等奖励"
start = 2025-02-03T12:00:00
end   = 2025-02-24T03:59:59
describe = "本次活动中，共有5处卷轴，对应5个战斗关卡。需要开拓者在不同的场景中找到对应的卷轴，进入战斗后击败故事中的对手。"

[[event]]
type = "活动"
name = "「花藏繁生」活动：拟造花萼限时双倍掉落"
start = 2025-02-14T04:00:00
end   = 2025-02-21T03:59:59
describe = "「花藏繁生」活动期间，挑战并通关「拟造花萼（金）」或「拟造花萼（赤）」时，可获得双倍奖励。"









