name = "门扉之启，王座之终"
version = "3.1"
special_program = 2025-02-14T19:30:00
update_time = 2025-02-26T06:00:00
wish_name = "活动跃迁"

[[wish]]
type = "角色"
name = "「径复原初」「掷山破云」"
start = 2025-02-26T11:00:00
end = 2025-03-19T11:59:59
describe = "「缇宝（同谐•量子）」「云璃（毁灭•物理）」"

[[wish]]
type = "光锥"
name = "「流光定影」「溯回忆象」"
start = 2025-02-26T11:00:00
end = 2025-03-19T11:59:59
describe = "「如果时间是一朵花（同谐）」「落日时起舞（毁灭）」"

[[wish]]
type = "角色"
name = "「血炬狮心」「令奉贞凶」"
start = 2025-03-19T12:00:00
end = 2025-04-08T15:00:00
describe = "「万敌（毁灭•虚数）」「藿蕾（丰饶•风）」"

[[wish]]
type = "光锥"
name = "「流光定影」「湖回忆象」"
start = 2025-03-19T12:00:00
end = 2025-04-08T15:00:00
describe = "「血火啊，燃烧前路（毁灭）」「惊魂夜（丰饶）」"

[[event]]
type = "活动"
name = "「嗷呜嗷呜事务所」活动"
start = 2025-02-28T12:00:00
end = 2025-04-07T03:59:59
describe = "在「嗷呜嗷呜事务所」中，开拓者将扮演奇美拉管理员，通过派遣适合的奇美拉参与工作，根据它们的特性调整队伍结构，提升奇美拉小队在花园中的队伍排名。"

[[event]]
type = "活动"
name = "「位面分裂」活动：位面饰品限时双倍掉落"
start = 2025-03-12T04:00:00
end = 2025-03-19T03:59:59
describe = "「位面分裂」活动期间，挑战「模拟宇宙」或「差分宇宙」时，可获得双倍奖励。"

[[event]]
type = "活动"
name = "「圣城鉴宝」：鉴定奥赫玛古玩获取星琼等奖励"
start = 2025-03-19T12:00:00
end = 2025-04-07T03:59:59
describe = "活动开启后，西塔罗斯将每日公开新的1种「待鉴定宝物」及协助鉴定所需的「鉴宝耗材」，宝物共计7种。"

[[event]]
type = "活动"
name = "「异器盈界」活动：隧洞遗器限时双倍掉落"
start = 2025-03-28T04:00:00
end = 2025-04-04T03:59:59
describe = "「异器盈界」活动期间，挑战并通关「侵蚀隧洞」时，可获得双倍奖励。"
