name = "走过安眠地的花丛"
version = "3.2"
special_program = 2025-03-28T19:30:00
update_time = 2025-04-09T06:00:00
wish_name = "活动跃迁"

[[wish]]
type = "角色"
name = "「冥途生花」「铭心之萃」"
start = 2025-04-09T11:00:00
end = 2025-04-30T11:59:59
describe = "「遐蝶（记忆·量子）」「忘归人（虚无·火）」「椒丘（虚无·火）」「黄泉（虚无·雷）」"

[[wish]]
type = "光锥"
name = "「流光定影」「真意之汇」"
start = 2025-04-09T11:00:00
end = 2025-04-30T11:59:59
describe = "「让告别，更美一些（记忆）」「长路终有归途（虚无）」「那无数个春天（虚无）」「行于流逝的岸（虚无）」"

[[wish]]
type = "角色"
name = "「胚中万物」「万物皆流」"
start = 2025-04-30T12:00:00
end = 2025-05-20T15:00:00
describe = "「那刻夏（智识·风）」「真理医生（巡猎·虚数）」"

[[wish]]
type = "光锥"
name = "「流光定影」「溯回忆象」"
start = 2025-04-30T12:00:00
end = 2025-05-20T15:00:00
describe = "「生命当付之一炬（智识）」「纯粹思维的洗礼（巡猎）」"
