name = "走过安眠地的花丛"
version = "3.2"
special_program = 2025-03-28T19:30:00
update_time = 2025-04-09T06:00:00
wish_name = "活动跃迁"

[[wish]]
type = "角色"
name = "「冥途生花」「铭心之萃」"
start = 2025-04-09T11:00:00
end = 2025-04-30T11:59:59
describe = "「遐蝶（记忆·量子）」「忘归人（虚无·火）」「椒丘（虚无·火）」「黄泉（虚无·雷）」"

[[wish]]
type = "光锥"
name = "「流光定影」「真意之汇」"
start = 2025-04-09T11:00:00
end = 2025-04-30T11:59:59
describe = "「让告别，更美一些（记忆）」「长路终有归途（虚无）」「那无数个春天（虚无）」「行于流逝的岸（虚无）」"

[[wish]]
type = "角色"
name = "「胚中万物」「万物皆流」"
start = 2025-04-30T12:00:00
end = 2025-05-20T15:00:00
describe = "「那刻夏（智识·风）」「真理医生（巡猎·虚数）」"

[[wish]]
type = "光锥"
name = "「流光定影」「溯回忆象」"
start = 2025-04-30T12:00:00
end = 2025-05-20T15:00:00
describe = "「生命当付之一炬（智识）」「纯粹思维的洗礼（巡猎）」"

[[event]]
type = "活动"
name = "「致开拓的你」：获取1600星琼&10燃料"
start = 2025-04-09T11:00:00
end = 2025-05-21T06:00:00
describe = "3.2版本更新后 至 2025/04/26 12:00 期间，开拓者可以在「致开拓的你」活动页面选择一位角色作为邀请对象，在后续收到其来信和赠礼。在此期间可以修改已选择的角色，超过此时间后无法进行选择或修改。"

[[event]]
type = "活动"
name = "「星铁☆WORLD」：经营展会获取4星光锥等奖励"
start = 2025-04-09T11:00:00
end = 2025-05-19T03:59:59
describe = "开拓者将在活动内的游戏中扮演策展人，经营「星铁☆WORLD」展会的分会场。"
