name = "在黎明升起时坠落"
version = "3.3"
special_program = 2025-05-09T19:30:00
update_time = 2025-05-21T06:00:00
wish_name = "活动跃迁"

[[wish]]
type = "角色"
name = "「虹隽晨昏」「视界来信」"
start = 2025-05-21T11:00:00
end = 2025-06-11T11:59:59
describe = "「风堇（记忆•风）」「大黑塔（智识•冰）」"

[[wish]]
type = "光锥"
name = "「流光定影」「溯回忆象」"
start = 2025-05-21T11:00:00
end = 2025-06-11T11:59:59
describe = "「愿虹光永驻天空（记忆）」「向着不可追问处（智识）」"

[[event]]
type = "活动"
name = "「银河球棒侠传说：魔王篇」活动说明"
start = 2025-05-21T11:00:00
end = 2025-06-30T03:59:59
describe = "本次活动有三个难度，累计六个战斗关卡。每个关卡有三个战斗阶段的若干波次敌人。 开拓者需要在有限轮次内，击败三个战斗阶段的指定数量敌人，完成关卡挑战。"
