ann_list_url = "https://hk4e-ann-api.mihoyo.com/common/hk4e_cn/announcement/api/getAnnList?game=hk4e&game_biz=hk4e_cn&lang=zh-cn&bundle_id=hk4e_cn&level=1&platform=pc&region=cn_gf01&uid=1"
ann_content_url = "https://hk4e-ann-api.mihoyo.com/common/hk4e_cn/announcement/api/getAnnContent?game=hk4e&game_biz=hk4e_cn&lang=zh-cn&bundle_id=hk4e_cn&level=1&platform=pc&region=cn_gf01&uid=1"

# 默认封面
default_post = "https://ys.mihoyo.com/main/_nuxt/img/holder.37207c1.jpg"

# 侧边栏图标
icon = "icon-yuanshen-heng"

# 游戏中英文名
[name]
en = "genshin"
zh = "原神"
