ann_list_url = "https://hkrpg-ann-api.mihoyo.com/common/hkrpg_cn/announcement/api/getAnnList?game=hkrpg&game_biz=hkrpg_cn&lang=zh-cn&bundle_id=hkrpg_cn&level=1&platform=pc&region=prod_gf_cn&uid=1"
ann_content_url = "https://hkrpg-ann-api.mihoyo.com/common/hkrpg_cn/announcement/api/getAnnContent?game=hkrpg&game_biz=hkrpg_cn&lang=zh-cn&bundle_id=hkrpg_cn&level=1&platform=pc&region=prod_gf_cn&uid=1"

# 默认封面
default_post = "https://ys.mihoyo.com/main/_nuxt/img/holder.37207c1.jpg"

# 侧边栏图标
icon = "icon-benghuai-hei"

# 游戏中英文名
[name]
en = "sr"
zh = "崩坏：星穹铁道"
