ann_list_url = "https://announcement-api.mihoyo.com/common/nap_cn/announcement/api/getAnnList?game=nap&game_biz=nap_cn&lang=zh-cn&bundle_id=nap_cn&level=1&platform=pc&region=prod_gf_cn&uid=1"
ann_content_url = "https://announcement-api.mihoyo.com/common/nap_cn/announcement/api/getAnnContent?game=nap&game_biz=nap_cn&lang=zh-cn&bundle_id=nap_cn&level=1&platform=pc&region=prod_gf_cn&uid=1"

# 默认封面
default_post = "https://ys.mihoyo.com/main/_nuxt/img/holder.37207c1.jpg"

# 侧边栏图标
icon = "icon-juequling-hei"

# 游戏中英文名
[name]
en = "zzz"
zh = "绝区零"
